### PR TITLE
Fix name

### PR DESCRIPTION
**Pull request by alex-voigt**
Hey, thanks for the credits! :-)

### CODE REVIEW

**Comment by antony** [comment]
Whoops! Sorry :)

**Comment by alex-voigt** [comment]
Well, [Jon](https://en.wikipedia.org/wiki/Jon_Voight) seems to be better known then me :-)

**Comment by antony** [comment]
Weirdly I can't merge this. I'll have to take a look into why!

**Comment by antony** [comment]
Ok, did it manually!

giphy

**Pull request closed without merging**
