### PR TITLE
Feature/datasource-rest

### PR DESCRIPTION
**Pull request by rand0me**
* Add ability to modify request headers

### CODE REVIEW

**Comment by rand0me** [comment]
Hello! I'm enjoying using `vudash` :smiley:, but for the last dashboard I'm stuck. My target REST service need `x-api-key` header, but I'm unable to set it :sob:. So here is PR to make it easy to customize request header sent to REST APIs

**Comment by antony** [comment]
Hi rand0me.

Great stuff - thanks for the PR!

**Comment by antony** [comment]
Done! Published a new version of the datasource - 7.4.0 :)

**Comment by rand0me** [comment]
Nice! :+1: Thanks for approving :rocket:

**Comment by antony** [comment]
Pleasure!

**Pull request merged**
